import { BulkImportEntityType } from '@/lib/bulk-import-schema';
import {
  bulkImportDevelopers,
  bulkImportProjects,
  bulkImportLayouts,
  bulkImportUnits,
  bulkImportPhases,
  bulkImportTowers,
  bulkImportSalesPackages,
  bulkImportTowerFacingGroups,
  bulkImportTowerStacks,
  bulkImportTowerSpecialFloors,
} from '@/app/actions/bulk-import-actions';
import type { BulkImportTemplateConfigMap } from '@/types/bulk-import.types';

export const BULK_IMPORT_ENTITY_CONFIG = {
  [BulkImportEntityType.DEVELOPER]: {
    label: 'Developers',
    action: bulkImportDevelopers,
    description: 'Create or update developer records before importing dependent project data.',
    templateCsvHeaders: ['action', 'slug', 'name', 'legalName', 'description', 'isActive'],
    templateSampleRow: [
      'create',
      'example-developer',
      'Example Developer Sdn. Bhd.',
      'Example Developer Holdings Berhad',
      'Township and residential developer',
      'true',
    ],
  },
  [BulkImportEntityType.PROJECT]: {
    label: 'Projects',
    action: bulkImportProjects,
    description: 'Create or update projects. The referenced developer slug must already exist.',
    templateCsvHeaders: [
      'action',
      'slug',
      'name',
      'displayName',
      'legalName',
      'description',
      'developerSlug',
      'propertyCategoryCode',
      'propertyTypeCode',
      'projectStatusCode',
      'tenureTypeCode',
      'titleTypeCode',
      'stateName',
      'regionName',
      'areaName',
      'address',
      'latitude',
      'longitude',
      'totalUnits',
      'launchYear',
      'bookingFee',
      'maintenanceFeePerSqft',
      'isPublished',
      'isForeignerEligible',
      'tenureExpiryDate',
    ],
    templateSampleRow: [
      'create',
      'example-project',
      'Example Project',
      'Example Project Residences',
      'Example Project Development Sdn. Bhd.',
      'Transit-oriented mixed development',
      'example-developer',
      'LANDED',
      'TERRACE',
      'UNDER_CONSTRUCTION',
      'FREEHOLD',
      'INDIVIDUAL',
      'Johor',
      'Johor Bahru',
      'Iskandar Puteri',
      '1 Example Avenue',
      '1.4927',
      '103.7414',
      '250',
      '2026',
      '2000',
      '0.35',
      'yes',
      'no',
      '',
    ],
  },
  [BulkImportEntityType.LAYOUT]: {
    label: 'Layouts',
    action: bulkImportLayouts,
    description: 'Create or update project layouts. Project slug must already exist.',
    templateCsvHeaders: [
      'action',
      'projectSlug',
      'layoutCode',
      'layoutName',
      'bedrooms',
      'bathrooms',
      'builtUpSqft',
      'studyRooms',
      'hasBalcony',
      'hasYard',
      'virtualTourUrl',
    ],
    templateSampleRow: [
      'create',
      'example-project',
      'A1',
      'Type A1',
      '3',
      '2',
      '1200',
      '1',
      'yes',
      'no',
      'https://example.com/tours/type-a1',
    ],
  },
  [BulkImportEntityType.UNIT]: {
    label: 'Units',
    action: bulkImportUnits,
    description: 'Create or update units. Project, lot type, and booking status references must exist.',
    templateCsvHeaders: [
      'action',
      'projectSlug',
      'layoutCode',
      'towerNumber',
      'phaseName',
      'unitNo',
      'floor',
      'stack',
      'displaySequence',
      'builtUpSqft',
      'landAreaSqft',
      'dimensionText',
      'facing',
      'positionType',
      'carparkCount',
      'carparkLotNo',
      'carparkType',
      'lotTypeCode',
      'bookingStatusCode',
      'basePrice',
      'finalPrice',
    ],
    templateSampleRow: [
      'create',
      'example-project',
      'A1',
      'TOWER-A',
      'Phase 1',
      '01-01',
      '1',
      'A',
      '1',
      '1200',
      '',
      '24 x 75',
      'North',
      'CORNER',
      '2',
      'CP-01,CP-02',
      'covered',
      'RESIDENTIAL',
      'AVAILABLE',
      '850000',
      '835000',
    ],
  },
  [BulkImportEntityType.PHASE]: {
    label: 'Phases',
    action: bulkImportPhases,
    description: 'Create or update project phases. Project slug must already exist.',
    templateCsvHeaders: ['action', 'projectSlug', 'phaseCode', 'phaseName', 'completionDate', 'constructionStatusCode'],
    templateSampleRow: ['create', 'example-project', 'P1', 'Phase 1', '2026-12-31', 'ONGOING'],
  },
  [BulkImportEntityType.TOWER]: {
    label: 'Towers',
    action: bulkImportTowers,
    description: 'Create or update towers. Project slug must already exist.',
    templateCsvHeaders: ['action', 'projectSlug', 'phaseName', 'towerNumber', 'towerName', 'floorCount', 'floorMin', 'floorMax'],
    templateSampleRow: ['create', 'example-project', 'Phase 1', 'TOWER-A', 'Tower A', '43', '3', '45'],
  },
  [BulkImportEntityType.SALES_PACKAGE]: {
    label: 'Sales Packages',
    action: bulkImportSalesPackages,
    description: 'Create or update promotion/sales packages. Project slug must already exist.',
    templateCsvHeaders: [
      'action',
      'projectSlug',
      'name',
      'buyerTypeCode',
      'rebatePercentage',
      'cashBackAmount',
      'validFrom',
      'validTo',
      'isActive',
    ],
    templateSampleRow: [
      'create',
      'example-project',
      'Early Bird Package',
      'LOCAL',
      '5.00',
      '10000',
      '2026-01-01',
      '2026-06-30',
      'true',
    ],
  },
  [BulkImportEntityType.TOWER_FACING_GROUP]: {
    label: 'Tower Facing Groups',
    action: bulkImportTowerFacingGroups,
    description: 'Define column-header facing bands for the unit availability chart. Tower must already exist.',
    templateCsvHeaders: ['action', 'projectSlug', 'towerNumber', 'key', 'label', 'sortOrder'],
    templateSampleRow: ['create', 'example-project', 'TOWER-A', 'lgc-left', 'Lake, Golf & City View', '0'],
  },
  [BulkImportEntityType.TOWER_STACK]: {
    label: 'Tower Stacks',
    action: bulkImportTowerStacks,
    description: 'Define stack (column) definitions for the unit availability chart. Tower and layout must already exist.',
    templateCsvHeaders: ['action', 'projectSlug', 'towerNumber', 'stackNo', 'layoutCode', 'builtUpSqft', 'facingGroupKey', 'sortOrder'],
    templateSampleRow: ['create', 'example-project', 'TOWER-A', '01', 'A1', '1200', 'lgc-left', '0'],
  },
  [BulkImportEntityType.TOWER_SPECIAL_FLOOR]: {
    label: 'Tower Special Floors',
    action: bulkImportTowerSpecialFloors,
    description: "Define breaktank (mechanical) and facility/podium rows for the unit chart. floorKind must be 'breaktank' or 'facility'.",
    templateCsvHeaders: ['action', 'projectSlug', 'towerNumber', 'floorKind', 'floorNumber', 'floorLabel', 'facilityLabel', 'sortOrder'],
    templateSampleRow: ['create', 'example-project', 'TOWER-A', 'breaktank', '33', 'BREAKTANK', '', '0'],
  },
} satisfies BulkImportTemplateConfigMap;

export const BULK_IMPORT_ENTITY_ORDER: BulkImportEntityType[] = [
  BulkImportEntityType.DEVELOPER,
  BulkImportEntityType.PROJECT,
  BulkImportEntityType.PHASE,
  BulkImportEntityType.TOWER,
  BulkImportEntityType.LAYOUT,
  BulkImportEntityType.UNIT,
  BulkImportEntityType.SALES_PACKAGE,
  BulkImportEntityType.TOWER_FACING_GROUP,
  BulkImportEntityType.TOWER_STACK,
  BulkImportEntityType.TOWER_SPECIAL_FLOOR,
];
